// import './5-object.js'
// import './6-animation.js'
// import './7-camera.js'
// import './8-fullscreen'
// import './9-geometries'
// import './10-debugger'
// import  './11-texture.js'
// import './12-material.js'
// import './13-3dText.js'

import './14-light.js'